import { useState } from "react";
import { useGetAllPersonsQuery, useGetFormFieldByFormCatIdQuery, useRegisterWithAutoGeneratedPasswordMutation, useUpdatePersonMutation, useDeletePersonMutation } from "../../store/api";
import { GenericCrudTable } from "../global/GenericCrudTable";
import { ModalForm } from "../global/ModalForm";
import { useForm } from "../global/hooks/useForm";
import { GenericAlert } from "../global/GenericAlert";

export const Persons = () => {

  //Calls de api

  const { data, isLoading } = useGetAllPersonsQuery();
  const { data: fields, isLoading: isFieldsLoading, isFetching } = useGetFormFieldByFormCatIdQuery(2); // ID del formulario
  const [createPerson] = useRegisterWithAutoGeneratedPasswordMutation();
  const [updatePerson] = useUpdatePersonMutation();
  const [deletePerson] = useDeletePersonMutation();

  const { initialValues, validationSchema } = useForm(fields, isLoading || isFetching);
  const [open, setOpen] = useState(false);
  const [selectedPerson, setSelectedPerson] = useState(null);
  const [alertOpen, setAlertOpen] = useState(false);
  const [alertSeverity, setAlertSeverity] = useState('success');
  const [alertMessage, setAlertMessage] = useState('');

  const handleOpen = (person = null) => {
    setSelectedPerson(person);
    setOpen(true);
  };

  const handleClose = () => {
    setOpen(false);
    setSelectedPerson(null);
  };

  const handleCloseAlert = () => {
    setAlertOpen(false);
  };

  const handleSubmit = async (values) => {
    try {
      let response;
      if (selectedPerson) {
        console.log("Selected person", selectedPerson);
        response = await updatePerson({ id: selectedPerson.id, token: selectedPerson.token + 'update', ...values }).unwrap();
      } else {
        response = await createPerson({ password: '****', token: '', typeId: values.rol, ...values }).unwrap();
      }

      setAlertSeverity('success');
      setAlertMessage(response.message || 'Operación completada con éxito');
      setAlertOpen(true);

      handleClose();
    } catch (error) {
      console.error("Error al guardar persona:", error);

      setAlertSeverity('error');

      if (error.data && error.data.errors) {
        const errorMessages = Object.values(error.data.errors).flat().join(', ');
        setAlertMessage(`Errores: ${errorMessages}`);
      } else if (error.data && error.data.title) {
        setAlertMessage(error.data.title);
      } else {
        setAlertMessage('Hubo un error al procesar la solicitud');
      }
      setAlertOpen(true);
    }
  };

  const handleDelete = async (id) => {
    try {
      let response;
      response = await deletePerson(id);

      setAlertSeverity('success');
      setAlertMessage(response.message || 'Operación completada con éxito');
      setAlertOpen(true);

    } catch (error) {
      console.error("Error al guardar persona:", error);

      setAlertSeverity('error');

      if (error.data && error.data.errors) {
        const errorMessages = Object.values(error.data.errors).flat().join(', ');
        setAlertMessage(`Errores: ${errorMessages}`);
      } else if (error.data && error.data.title) {
        setAlertMessage(error.data.title);
      } else {
        setAlertMessage('Hubo un error al procesar la solicitud');
      }
      setAlertOpen(true);
    }
  }

  const columns = [
    { field: "id", headerName: "ID", flex: 1 },
    { field: "nombres", headerName: "Nombres", flex: 1 },
    { field: "apellidos", headerName: "Apellidos", flex: 1 },
    { field: "email", headerName: "Email", flex: 1 },
    { field: "telefono", headerName: "Teléfono", flex: 1 },
    { field: "fechaNacimiento", headerName: "Fecha de Nacimiento", flex: 1 },
  ];

  return (
    <>
      <GenericCrudTable
        data={data?.data || []}
        columns={columns}
        onAdd={() => handleOpen()}
        onEdit={(row) => handleOpen(row)}
        onDelete={(id) => handleDelete(id)}
        isLoading={isLoading}
        title="Lista de Personas"
        subTitle="Gestión de personas registradas"
      />

      <ModalForm
        open={open}
        onClose={handleClose}
        title={selectedPerson ? "Editar Persona" : "Agregar Persona"}
        formFields={fields?.data || []}
        initialValues={selectedPerson || initialValues}
        validationSchema={validationSchema} // Agrega validaciones si es necesario
        onSubmit={handleSubmit}
        submitButtonText={selectedPerson ? "Actualizar" : "Agregar"}
        isLoading={isFieldsLoading}
        error={null} // Puedes manejar errores aquí
      />

      <GenericAlert
        open={alertOpen}
        onClose={handleCloseAlert}
        severity={alertSeverity}
        message={alertMessage}
      />

    </>
  );
};
