import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react';

const baseQuery = fetchBaseQuery({
  baseUrl: import.meta.env.VITE_API_BASE_URL,
  prepareHeaders: (headers, { getState }) => {
    const token = getState().auth.authToken;
    if (token) {
      headers.set('Authorization', `Bearer ${token}`);
    }
    return headers;
  },
});

export const personasApi = createApi({
  reducerPath: 'personasApi',
  baseQuery: baseQuery,
  tagTypes: ['Personas'],
  endpoints: (builder) => ({
    authenticatePerson: builder.mutation({
      query: (data) => ({
        url: 'Personas/Authenticate',
        method: 'POST',
        body: data,
      }),
    }),
    registerPerson: builder.mutation({
      query: (data) => ({
        url: 'Personas/Register',
        method: 'POST',
        body: data,
      }),
      invalidatesTags: ['Personas'],
    }),
    registerWithAutoGeneratedPassword: builder.mutation({
      query: (data) => ({
        url: 'Personas/CreateWithAutoGeneratedPassword',
        method: 'POST',
        body: data,
      }),
      invalidatesTags: ['Personas'],
    }),
    getAllPersons: builder.query({
      query: () => 'Personas/GetAll',
      providesTags: ['Personas'],
    }),
    getPersonById: builder.query({
      query: (id) => `Personas/GetById/${id}`,
      providesTags: ['Personas'],
    }),
    updatePerson: builder.mutation({
      query: (data) => ({
        url: 'Personas/Update',
        method: 'PUT',
        body: data,
      }),
      invalidatesTags: ['Personas'],
    }),
    deletePerson: builder.mutation({
      query: (id) => ({
        url: `Personas/Delete/${id}`,
        method: 'DELETE',
      }),
      invalidatesTags: ['Personas'],
    }),
  }),
});

export const {
  useAuthenticatePersonMutation,
  useRegisterPersonMutation,
  useRegisterWithAutoGeneratedPasswordMutation,
  useGetAllPersonsQuery,
  useGetPersonByIdQuery,
  useUpdatePersonMutation,
  useDeletePersonMutation,
} = personasApi;
